### ISSUE TITLE
Favicon has no background

### ISSUE THREAD

**Issue by mueller-ma** [openhab/website#11]
Without a background the openHAB logo has hardly readable in dark browser themes. @ghys You can use https://realfavicongenerator.net/ to generate and check favicons for all needs.

**Comment by kaikreuzer** [comment]
Simply use the one from the current website: https://raw.githubusercontent.com/openhab/openhab.github.io/master/favicon.ico

**Comment by ghys** [comment]
Yep, thanks, I had this on my mind ;)

**Comment by kaikreuzer** [comment]
This seems to be fixed meanwhile.
