### ISSUE TITLE
Chocolatey 2.3 installation procedure should not be recommended in it's current form

### ISSUE THREAD

**Issue by joostwestra** [openhab/website#115]
The current installation page:
https://www.openhab.org/download/

Currently mentions Chocolatey as the first installation option.
However this package in it's current form should not be used:
It installs all bindings and UI's by default. 
Some of these bindings also give error's when running on WIndows.

Recommended solutions:
A. Remove the Chocolatey procedure from the downloads page
B. Fix the package to not install all bindings by default.

More Info.
https://community.openhab.org/t/unsure-about-installation-procedures-for-windows/46232

**Comment by AngelosF** [comment]
By the way: I think that the root-cause is: https://github.com/openhab/openhab-distro/issues/729

Since tools\ChocolateyInstall.ps1 downloads openhab-addons-2.3.0.kar and places it in the addons folder.

Ref: https://chocolatey.org/packages/openhab

Note: There is a new effort to build a new installer for Win: https://github.com/openhab/openhab-distro/issues/807

**Comment by ghys** [comment]
I created https://github.com/bcurran3/ChocolateyPackages/pull/51, if it's all it takes to fix the problem maybe @bcurran3 can update the package - I'll remove the Chocolatey section from the website in a few days if the problem persists.

In any case when the Inno installer is ready it'll be the preferred way to install - and the Chocolatey package should probably use it.

**Comment by tmrobert8** [comment]
Feel free to comment on the installer issue as I'm trying to layout the exact scope of what it should do...

**Comment by ghys** [comment]
The Chocolatey package no longer downloads the offline addons kar file - see https://github.com/bcurran3/ChocolateyPackages/pull/51.
Furthermore, https://github.com/openhab/website/pull/123 de-emphasizes Chocolatey (until the new installer is ready) and adds a warning that it's not an officially supported installation method.

So I think this issue can be closed.
