### ISSUE TITLE
Some "Edit this page on GitHub" links still edit ESH files

### ISSUE THREAD

**Issue by wborn** [openhab/website#164]
This is for example an issue on the [Units Of Measurement](https://www.openhab.org/docs/concepts/units-of-measurement.html) concepts page when clicking 
"Edit this page on GitHub" at the bottom of the page.

The link opens:

https://github.com/eclipse/smarthome/edit/master/docs/documentation/concepts/units-of-measurement.md

It looks like that content was already migrated in https://github.com/openhab/openhab-docs/pull/890?

**Comment by ghys** [comment]
Thanks!
