### ISSUE TITLE
How to embed images for/in addon readmes?

### ISSUE THREAD

**Issue by davidgraeff** [openhab/website#173]
At the moment the addons page does not render the embedded images of the mqtt readme.
See https://github.com/openhab/openhab2-addons/tree/master/bundles/org.openhab.binding.mqtt.generic

and https://www.openhab.org/addons/bindings/mqtt.generic/

**Comment by ghys** [comment]
The build is broken atm because of https://github.com/openhab/openhab-docs/issues/937

**Comment by ghys** [comment]
Closing as fixed by https://github.com/openhab/openhab-docs/pull/938.
