### ISSUE TITLE
Tab-Style possible?

### ISSUE THREAD

**Issue by Confectrician** [openhab/website#183]
Hi,

Is it possible to add tabs in the standard theme?
I would love to have to ability to save rule examples in more than one rule language we support.

This was my idea of how it could look:
![rulesTabs](https://user-images.githubusercontent.com/7161177/57016926-fd88dd00-6c1c-11e9-8f4f-4c4f6a513abd.gif)

Would be very nice, if this would work in theory.
If yes, we would have to find a way to reflect this in our markdown files, but i will start thinking about it when i have an answer here.
Doesn't make sense to do so, when it isn't possible with vuepress.

**Comment by ghys** [comment]
That's probably possible with a Vue component at first sight, not entirely sure though.

**Comment by Confectrician** [comment]
I am self learning Vue out of interest currently, but did not yet investigate time into components.
I will have an eye open when i am at that point. :)

**Comment by openhab-5iver** [comment]
ECMAScript would be more accurate. I took [this comment](https://github.com/lewie/openhab2-javascript/issues/4#issuecomment-481369691) to mean "Use ECMAScript" and is how I was planning to setup the repo. Or did I get it wrong?

**Comment by Confectrician** [comment]
Thanks for the feedback @openhab-5iver.
But as already stadet above this justa showcase example and we can start talking about the "how", when we have found a way to do this generally.

**Comment by openhab-5iver** [comment]
OK! BTW, this looks great and will be very useful. I can also imagine Beginner/Advanced/Expert tabs.

**Comment by ghys** [comment]
Just had another look at this and stumbled across https://github.com/pskordilakis/vuepress-tabs - this looks like exactly what we want. I can have a look at including it for a quick-win solution.
One caveat is the underlying component to render the tabs is not maintained anymore. It will probably work well enough though until major framework upgrades are performed on the site. [It looks like this](http://vue-tabs-component.spatie.be).

If we ever decide to upgrade to VuePress 1.0 from 0.9 - probably a non-trivial change so planned but no commitment yet - the good news is, there's a [equivalent plugin](https://github.com/pskordilakis/vuepress-plugin-tabs).
