### ISSUE TITLE
Update ESH reference on opening page

### ISSUE THREAD

**Issue by wborn** [openhab/website#196]
When you scroll down the [opening page](https://www.openhab.org/) there is a reference to ESH that needs an update because of the fork and ESH no longer being actively maintained:

![esh](https://user-images.githubusercontent.com/12213581/59150818-bc5cc780-8a29-11e9-8904-44d9e0314256.png)

**Comment by ghys** [comment]
This has been on the back of my mind for some time actually :) Wonder if we should simply remove it or remove the logo and change the text to something else.

**Comment by ghys** [comment]
I'll remove it from the home page without deleting the code for now.

**Comment by wborn** [comment]
It would be nice if we had some other logos and accompanying text to make the point that openHAB is "100% Open Source. 100% Reliable." These remain some of the important unique selling points. :-)

**Comment by davidgraeff** [comment]
We already say that openHAB is open source on the same page. I wouldn't put reliable on the frontpage until 2.5.2 is out.

**Comment by wborn** [comment]
Do you still want to keep this issue open @ghys? It is sort of solved because the ESH reference got commented in https://github.com/openhab/website/pull/197. If it were completely removed this issue could be closed for sure. :wink:

**Comment by ghys** [comment]
Yes, you're right, thanks!
