### ISSUE TITLE
Add support for dark mode

### ISSUE THREAD

**Issue by wborn** [openhab/website#207]
At night the website (especially [documentation](https://www.openhab.org/docs/)) can be blinding to the eyes. Maybe we can also support dark mode?

Such a user preference can be detected using the [prefers-color-scheme](https://drafts.csswg.org/mediaqueries-5/#prefers-color-scheme) user preference media query. Detection is currently supported by ~76% of all browsers used world wide (see [caniuse](https://caniuse.com/#search=prefers-color-scheme)). For some examples see also [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme).

**Comment by Confectrician** [comment]
I have found https://github.com/tolking/vuepress-theme-default-prefers-color-scheme which seems to add the prefers-colors-scheme mediea query to the default theme.
Also this is discussed in  an vuepress issue already.
Ref:
https://github.com/vuejs/vuepress/issues/1865

**Comment by ghys** [comment]
This plugin is for VuePress 1.x ;)
We're still on 0.x, 1.x has quite a few differences, so there should be some breaking changes to expect and we'll have to be careful if/when we migrate.

**Comment by Confectrician** [comment]
I think we had some more issues where 1.x was topic.
We should maybe think about doing an update anyways in the nearer future.

**Comment by wborn** [comment]
I see https://next.openhab.org/ now has a proper dark mode so this issue should be fixed soon. :sunglasses:
