### ISSUE TITLE
status.openhab.org not available

### ISSUE THREAD

**Issue by wborn** [openhab/website#232]
Hi @openhab/foundation-staff! The status page isn't available through either 

http://status.openhab.org/ or https://status.openhab.org/

On the HTTP site it shows:

> ## Public Status for This Site Is Not Available
>
> Dear visitor,
>
> If you are owner of this website and you created this status page please login into your AppBeat account, click on "Public status" module and enable it from there.
>
> If you need monitoring and public status for your own website please visit www.appbeat.io and sign up for free trial.
>
> Thank you,
> AppBeat Team

**Comment by kaikreuzer** [comment]
Seems the account didn't auto-renew.
Just tried to renew it manually, but failed. Need to wait for their customer support first...

**Comment by wborn** [comment]
The status page is available again @kaikreuzer! :smiley: :tada:
