### ISSUE TITLE
Adapt website to 3.0

### ISSUE THREAD

**Issue by lsiepel** [openhab/website#251]
https://www.openhab.org/download/ 
Select windows 3.0.0 snapshot 
The big download snapshot button contains a link to 2.5.0 integration build page, it should be:
https://ci.openhab.org/view/Integration%20Builds%20(3.x)/job/openHAB3-Distribution/

Or even better:
https://ci.openhab.org/view/Integration%20Builds%20(3.x)/job/openHAB3-Distribution/lastSuccessfulBuild/artifact/distributions/openhab/target/openhab-3.0.0-SNAPSHOT.zip

It also refers to zulu-8 while 3.0.0 requires 11 or am i mistaken?

Same is happening for the macOs download button.

**Comment by ghys** [comment]
There's a new site for openHAB 3 - https://next.openhab.org

**Comment by lsiepel** [comment]
Maybe it is good to fix the links until this new site replaces the current one? The new site will be released at the same time as 3.0.0 stable?

**Comment by lsiepel** [comment]
Fixed with https://github.com/openhab/website/pull/253 and https://github.com/openhab/website/pull/252
