### ISSUE TITLE
Expired Certificate: demo.openhab.org

### ISSUE THREAD

**Issue by kojid0** [openhab/website#272]
Looks like your certificate of https://demo.openhab.org/ has expired since February 07, 2021.

**Comment by kaikreuzer** [comment]
Thanks for noticing - already tracked here: https://github.com/openhab/website/issues/273

**Comment by kojid0** [comment]
> Thanks for noticing - already tracked here: #273

Now I see it too. It was in openhab/openhab-distro before.
