### ISSUE TITLE
Certificate of demo.openhab.org expired

### ISSUE THREAD

**Issue by mueller-ma** [openhab/website#273]
When visiting https://demo.openhab.org/ I get an expiration error: 
![grafik](https://user-images.githubusercontent.com/22525368/107365084-98923480-6adc-11eb-81eb-a9aa163f5732.png)

By the way: Is this the correct repo to open issues for the demo server?

**Comment by ghys** [comment]
Done. I saw a cronjob that was supposed to renew automatically but with the upgrade of the demo it (obviously) didn't work anymore. I _think_ I made some changes and fixed it, we'll see in 3 months!

**Comment by ghys** [comment]
> By the way: Is this the correct repo to open issues for the demo server?

This wasn't really decided tbh but let's close this debate right now and say that it is :)

**Comment by mueller-ma** [comment]
> we'll see in 3 months!

I used to configure (and I thinks it the default setup) certbot to renew certs if the expire in less than 30 days.

**Comment by kaikreuzer** [comment]
> and say that it is :)

While I had meanwhile moved it to the website repo ;-) 

Thanks for renewing it, @ghys!
