### ISSUE TITLE
Redirect http -> https

### ISSUE THREAD

**Issue by mueller-ma** [openhab/website#279]
When I visit http://www.openhab.org/ there's no redirect to https. This should be done for security reasons and to get rid of browser warnings, e.g. Firefox: "Connection not secure".

**Comment by Confectrician** [comment]
Hm i am getting a redirect.

Which browser did you test it with?

**Comment by mueller-ma** [comment]
Now I'm getting a redirect in Firefox and curl:
````bash
$ curl --silent www.openhab.org
Redirecting to https://www.openhab.org/
````

**Comment by Confectrician** [comment]
My Firefox test was succesful too, after applying an update.
