### ISSUE TITLE
Schema validation files are offline

### ISSUE THREAD

**Issue by frederictobiasc** [openhab/website#281]
Hi,
the maven build of my plugin throws several warnings since the XML-Schema-Files are currently unreachable, for instance https://openhab.org/schemas/thing-description-1.0.0.xsd

Excerpt of the output:
```
[ERROR] Unable to get XSD file https://openhab.org/schemas/binding-1.0.0.xsd : Unable to get https://openhab.org/schemas/binding-1.0.0.xsd
java.io.IOException: Unable to get https://openhab.org/schemas/binding-1.0.0.xsd
[...]
Caused by: java.io.IOException: Server returned HTTP response code: 525 for URL: https://www.openhab.org/schemas/binding-1.0.0.xsd
[...]
[ERROR] Unable to get XSD file https://openhab.org/schemas/thing-description-1.0.0.xsd : Unable to get https://openhab.org/schemas/thing-description-1.0.0.xsd
java.io.IOException: Unable to get https://openhab.org/schemas/thing-description-1.0.0.xsd
[...]
Caused by: java.io.IOException: Server returned HTTP response code: 525 for URL: https://www.openhab.org/schemas/thing-description-1.0.0.xsd
[...]
[ERROR] Unable to get XSD file https://openhab.org/schemas/config-description-1.0.0.xsd : Unable to get https://openhab.org/schemas/config-description-1.0.0.xsd
[...]
Caused by: java.io.IOException: Server returned HTTP response code: 525 for URL: https://www.openhab.org/schemas/config-description-1.0.0.xsd
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0 (HttpURLConnection.java:1924)
[...]
[WARNING] XML validation will be skipped as the schema file download failed.
[WARNING] XML validation will be skipped as the schema file download failed.
```
I created my "thing-xml" based on the documentation [here](https://www.openhab.org/docs/developer/bindings/thing-xml.html#xml-structure-for-thing-descriptions).

**Comment by Confectrician** [comment]
Hi,

Schemas are stored here: https://github.com/openhab/website/tree/main/.vuepress/public/schemas

I have tried to reach all 3 xsd schemas via browser now and they are available for me.
Could you test them in the browser too?

**Comment by Confectrician** [comment]
Could also be related to https://github.com/openhab/openhab-core/issues/1239 and probably a issue with our cdn.

cc @kaikreuzer

**Comment by frederictobiasc** [comment]
Hi and thanks for your quick reply. I can confirm that they are online now.
In general, I have frequent issues when visiting openhab.org. I get the cloudflare error page, stating that the server is not reachable.

**Comment by kaikreuzer** [comment]
@Confectrician "browser integrity check" is still disabled, so this does not seem to be the issue.

**Comment by frederictobiasc** [comment]
![openhab-offline](https://user-images.githubusercontent.com/26125115/115149240-7e884b80-a063-11eb-99a6-62f8545521f8.png)
