### ISSUE TITLE
Docker install Windows (cmd) version

### ISSUE THREAD

**Issue by M123-dev** [openhab/website#295]
When installing openHab on Docker, on Windows the command does not work since cmd does not use `/` but `^` for a new line. I think it would be nice for windows users if this is either noted, or even better a separate code field is provided.

**Comment by Confectrician** [comment]
This also affects the documentation article https://github.com/openhab/openhab-docs/commits/main/installation/docker.md shown as https://www.openhab.org/docs/installation/docker.html on the website.

The examples on dockerhub also only use the linux syntax.

Maybe we could add a "Note" box before the examples to inform about this.

Could look similar to this existing one:
![image](https://user-images.githubusercontent.com/7161177/118868075-0de38180-b8e4-11eb-8468-94d7e635136d.png)

@ghys do we have to rebuild this in the install instructions page on our own?
I think it is a vue component, iirc.

**Comment by M123-dev** [comment]
How about we provide a separate guide for Docker on Windows where we also point out other things like that the port needs to be exposed. We can then refer to this in the "Note" box.

**Comment by Confectrician** [comment]
This could be a proper usecase for our tabbing features.
I will provide a Draft for our docs article, to see how it will look.

**Comment by Confectrician** [comment]
https://github.com/openhab/openhab-docs/pull/1581

**Comment by M123-dev** [comment]
Okay the problem of the issue is fixed, the hint you suggested could be added but I think we can close the issue here. Thanks for your support
