### ISSUE TITLE
Broken html anchor on /download

### ISSUE THREAD

**Issue by mueller-ma** [openhab/website#303]
1. Go to https://www.openhab.org/download/
2. Select Raspberry Pi
3. The link of "launch a hotspot" goes to https://www.openhab.org/docs/installation/openhabian.html#wifi-hotspot, but should go to https://www.openhab.org/docs/installation/openhabian.html#wi-fi-hotspot (added dash in wi-fi).

I'd open a PR, but I haven't found this file here or in https://github.com/openhab/openhab-docs. And there's no "Edit on GitHub" link.

**Comment by Confectrician** [comment]
Sorry for the delay @mueller-ma i completely missed this small one.

The download and install page is maintained in the `.vuepress` folder as a component.
I have added a PR to fix the anchor.
