### ISSUE TITLE
RSS feed for blog

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/website#31]
Hey, I'm totally aware that the whole page is far from done and you've done a tremendous job so far. Just in case you were not aware yet, the blog (an area I especially wanted for the new page) does not yet offer an RSS/Atom feed. No stress ;)

**Comment by ghys** [comment]
I discussed this with Kai earlier this week, and I'm a heavy RSS user myself so definitely would like to see this happen. VuePress has [blogging support](https://github.com/vuejs/vuepress#todo-features) on the roadmap (there are a number of issues in the GitHub repo about this) so I was waiting to see what would come out of it. Eventually generating a feed from pages in the blog folder and putting it among the static files could be handled by some script during the build phase.

**Comment by t-8ch** [comment]
There is now a plugin to support this: https://github.com/webmasterish/vuepress-plugin-feed

**Comment by gitMiguel** [comment]
Still on 0.9.x?

**Comment by stefan-muc** [comment]
Yeah would like to see that too!
