### ISSUE TITLE
Manual Installation Snapshot link goes to 3.2.0

### ISSUE THREAD

**Issue by jimtng** [openhab/website#334]
The current download on https://www.openhab.org/download/ for the snapshot links to https://ci.openhab.org/job/openHAB3-Distribution/lastSuccessfulBuild/artifact/distributions/openhab/target/openhab-3.2.0-SNAPSHOT.zip

**Comment by kaikreuzer** [comment]
Good catch, thanks for noticing! I've created https://github.com/openhab/website/pull/335 as a fix!
