### ISSUE TITLE
Forum is broken: "your browser is too old to work on this site"

### ISSUE THREAD

**Issue by Nadahar** [openhab/website#355]
While community.openhab.org worked perfectly fine yesterday, today I can't log in because my browser is "too old". There was never any warning, I was locked out over night.

I don't know if this is the right place to "report" this, I also expect that I will get "just upgrade" as a reply. I can't upgrade, since Firefox has a breaking bug (for me) that hasn't been addressed yet: https://bugzilla.mozilla.org/show_bug.cgi?id=1678867

I can't imagine that there is any "real" problem here, this browser works perfectly fine all over the web for me. So, somebody has probably just decided to set some arbitrary minimum version for whatever reason, and it's really sad to be locked out for "no good reason". There can be lots and lots of reasons why people can't upgrade.

**Comment by hmerk** [comment]
We have updated discourse version 10 hours ag, cause of a security advisory.
https://meta.discourse.org/c/feature/announcements/67
I can‘t see any option to make limitations for browser versions.

**Comment by Nadahar** [comment]
Ok, so what you're saying is that discourse is dictating this and that whenever there's a security issue with discourse, you have to accept their arbitrary browser limitations at the same time?

In the meanwhile I've faked my user-agent, which makes the forum work again. It's just so sad to see how dysfunctional this whole push to "use the latest security patches" have become. If somebody decides to break something because they don't care about it (which happens all the time with various software), everybody else is effectively forced to submit to the decision because otherwise they will be frozen out "due to security concerns". I sort of expect this from commercial actors, which use the same mechanism to increase revenue by limiting software and making sure that you have to buy things that used to be a part of something else, or introduce "lease" instead of "buy" schemes etc. I expect better from open-source though. This isn't specific for openHAB though, but rather an "increasing trend" I've seen in many open-source projects in the last years.

The fact that the forum seems to work just fine with a faked user-agent clearly shows how arbitrary this is.

**Comment by Nadahar** [comment]
I won't bother to discuss it with discourse, since I already know their motivation. They're a commercial company and they don't want to spend money on supporting anything but the latest versions. They simply see it as a waste of money, and find it easier to force people to comply.

I'm sure they could find some excuse if one took it far enough, some "new" function that they just "have to" use and that it is simply "unsustainable" for them to provide a backwards compatible solution for. It's quite likely that this doesn't even affect your use, and if it does, it might be some very minor thing that doesn't even matter.

The funny thing is that I can't even raise it with them if I wanted to, without faking my user-agent, because I'm locked out there as well, obviously.

I'm not sure I agree that there's nothing you can do about it, you have chosen to accept discourse's "rules". I do understand that you probably don't care or think it's an irrelevant problem, because it doesn't affect any of you - this time. This is a much broader problem though, which affects a lot of people when you add all the different "small problems" that prevent people from running the latest versions together.

**Comment by Nadahar** [comment]
I'm not saying that you should change the forum software, I'm simply saying that this is one of the things you have to take into consideration when you chose (forum) software. What restrictions does this pose - what can we do to mitigate, or do we simply accept the limitations.

I have no illusions that this will lead anywhere, I'm just saying that it's "out of your hands" by choice. I think that's an important point, and I think it's sad that this will exclude me, and others in a similar situation, from the forum in the long term. The user-agent hack works for now, so that's fine for me, but I'm sure that at some point it will break too.

That said, I don't think the Firefox bug is minor, and I don't quite understand how most people ignore this. When I created the issue, I tried to give them a simple, reproducible example. The problem is much wider, essentially SVG rendering has been broken in Firefox since then.
