### ISSUE TITLE
Forum down

### ISSUE THREAD

**Issue by morph166955** [openhab/website#395]
I'm not sure if this is the correct place, but I couldn't find one more appropriate and I haven't seen a notice on the main webpage or anywhere else giving indication of an issue.  The forum has been down for some time now for me (probably close to 8 hours if not more).  Curious as to what's going on.

![Screenshot 2023-02-12 164442](https://user-images.githubusercontent.com/53797132/218341816-45820133-ba67-4430-8a85-a6d2a33cc200.png)

**Comment by kaikreuzer** [comment]
It is what it says: "we are currently upgrading the site".
It is much more tricky than expected, but I hope to have it up soon again.
