### ISSUE TITLE
Consent Banner Refactoring introduced some CSS issues

### ISSUE THREAD

**Issue by simonwes** [openhab/website#428]
I think some of the changes in #423 affect the CSS of the rest of the website. Links are now yellow:
![image](https://github.com/openhab/website/assets/37214166/c7dfc500-f98f-4180-a606-073851e26927)

Font of p looks different than for li:
![image](https://github.com/openhab/website/assets/37214166/3cdff973-6e02-4f1b-a070-91952922c9ba)

maybe more.

**Comment by florian-h05** [comment]
Fixed by https://github.com/openhab/website/pull/429.

**Comment by florian-h05** [comment]
@kaikreuzer Can you please close that issue then?
