### ISSUE TITLE
Link to classic icon set broken

### ISSUE THREAD

**Issue by mherwege** [openhab/website#47]
In the new [documentation](https://www.openhab.org/docs/configuration/items.html#icons), the link to the [classic icons ](https://www.openhab.org/docs/configuration/items.html)takes you back to the main [openhab.org ](https://www.openhab.org/)page. This [link ](https://docs.openhab.org/v2.2/addons/iconsets/classic/readme.html)went missing.

**Comment by gitMiguel** [comment]
I checked those links and they seem to work now. Can this be closed @mherwege ?

**Comment by mherwege** [comment]
Yes, looks fine now.
