### ISSUE TITLE
The MQTT1 binding is considered superseded by the new unreleased one

### ISSUE THREAD

**Issue by ghys** [openhab/website#81]
Since last deployment, the new MQTT binding from ESH has been imported:
https://www.openhab.org/addons/bindings/mqtt/

And this has automatically superseded the former 1.x binding, which doesn't appear in lists and the sidebar anymore (unless "show legacy bindings" is checked):
https://www.openhab.org/addons/bindings/mqtt1/

I'm not sure it's correct.

Also, the "edit link" page is wrong - it thinks it's an openHAB 2 binding; the reason is because it doesn't appear yet in https://github.com/openhab/openhab-distro/blob/master/features/addons-esh/src/main/feature/feature.xml which is used to determine which bindings are from ESH.

**Comment by kaikreuzer** [comment]
You are right - the ESH MQTT binding is still work in progress and thus not part of the openHAB distro (and therefore should not appear in the docs).
Would it be feasible to filter the ESH bindings to include only the ones that appear in https://github.com/openhab/openhab-distro/blob/master/features/addons-esh/src/main/feature/feature.xml? Alternatively, we could add an exclude in the copy process from the ESH repo.

**Comment by ghys** [comment]
> Alternatively, we could add an exclude in the copy process from the ESH repo.

Indeed the fundamental problem is that it's been added to https://github.com/openhab/openhab-docs/tree/final/_addons_bindings - in all theory it shouldn't until it's part of the openHAB distro.

All bindings appearing there are considered for the docs, and
https://github.com/openhab/openhab-distro/blob/master/features/addons-esh/src/main/feature/feature.xml is only used to determine whether it comes from ESH or not (if a binding is not an ESH feature according to that file, and it doesn't have an OH1 source in the front matter, then it's considered to be an OH2 binding).

I can probably set up some sort of "temporary ignore list" in the Ruby script preparing the docs for the website too - it's only a few lines of code.

**Comment by kaikreuzer** [comment]
> I can probably set up some sort of "temporary ignore list" in the Ruby script preparing the docs for the website too - it's only a few lines of code.

👍

**Comment by ghys** [comment]
Done. Let's not forget to remove it from the list when it's ready ;)

**Comment by Confectrician** [comment]
>Done. Let's not forget to remove it from the list when it's ready ;)

Don't worry. Someone will complain sooner or later. 😄
